use crate::utils::serde_utils::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
pub struct Product {
    pub product: String,
    pub category_ids: Vec<i32>,
    pub main_category: i32,
    pub price: String,
    #[serde(deserialize_with = "deserialize_string_or_int_to_i32")]
    pub company_id: i32,
    pub status: String,
    #[serde(deserialize_with = "deserialize_string_or_int_to_i32")]
    pub amount: i32,
    pub avail_since: String,
    pub box_height: Option<i32>,
    #[serde(deserialize_with = "deserialize_string_or_int_to_i32")]
    pub length: i32,
    pub box_width: Option<i32>,
    pub details_layout: String,
    pub edp_shipping: String,
    pub exceptions_type: String,
    pub free_shipping: String,
    pub full_description: Option<String>,
    //  TODO image_pairs
    pub is_dep: Option<String>,
    pub lang_code: Option<String>,
    #[serde(deserialize_with = "deserialize_string_or_float_to_f32")]
    pub list_price: f32,
    pub list_qty_count: String,
    pub localisation: Option<String>,
    pub low_avail_limit: String,
    // TODO main_pair
    pub max_qty: String,
    pub max_items_in_box: Option<i32>,
    pub meta_description: Option<String>,
    pub meta_keywords: Option<String>,
    pub min_items_in_box: Option<i32>,
    #[serde(deserialize_with = "deserialize_string_or_int_to_i32")]
    pub min_qty: i32,
    pub options_type: Option<String>,
    pub out_of_stock_actions: String,
    pub page_title: Option<String>,
    pub point_price: Option<String>,
    pub popularity: Option<String>,
    pub product_code: String,
    // TODO product_features
    #[serde(deserialize_with = "deserialize_string_or_int_to_i32")]
    pub product_id: i32,
    pub promo_text: Option<String>,
    #[serde(deserialize_with = "deserialize_string_or_int_to_i32")]
    pub qty_step: i32,
    pub return_period: String,
    pub sales_amount: Option<String>,
    pub search_words: Option<String>,
    pub seo_name: String,
    pub shared_product: Option<String>,
    pub shipping_freight: String,
    pub shipping_params: String,
    pub short_description: Option<String>,
    #[serde(deserialize_with = "deserialize_string_or_int_to_vec_i32")]
    pub tax_ids: Vec<i32>,
    pub timestamp: String,
    pub tracking: Option<String>,
    pub unlimited_download: String,
    pub updated_timestamp: String,
    #[serde(deserialize_with = "deserialize_string_or_int_to_vec_i32")]
    pub usergroup_ids: Vec<i32>,
    #[serde(deserialize_with = "deserialize_string_or_float_to_f32")]
    pub weight: f32,
    pub zero_price_action: String,
}
