on: [ push ]
name: CI


env:
  CSCART_API_KEY: ${{ secrets.CSCART_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check cargo toolchain
        run: |
          echo $CSCART_API_KEY
          cargo --version
          cargo test
          if [ $? -eq 0 ]; then
            echo "Tests were successfull"
          fi

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action