on: [ push ]
name: CI


env:
  CSCART_API_KEY: ${{ secrets.CSCART_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $CS_CART_API_KEY

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action