on: [ push ]
name: CI
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      env:
        CSCART_API_KEY: ${{ secrets.CS_CART_API_KEY }}
      - uses: actions/checkout@v3
      - run: cargo test

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action