on: 
  push: 
    branches-ignore:
      - 'release-plz-*'
name: CI

env:
  CSCART_API_KEY: ${{ secrets.CSCART_API_KEY }}
  CSCART_USERNAME: ${{ secrets.CSCART_USERNAME }}
  CSCART_HOST: ${{ secrets.CSCART_HOST }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test