on:
  release:
    types:
      - created
env:
  CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

jobs:
  publish:
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - name: Publish to crates.io
        run: |
          cargo login -t CRATES_IO_API_TOKEN
          cargo publish
