name: Release package crates.io
on: workflow_dispatch
env:
  CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to crates.io
        run: cargo publish --token ${CRATES_IO_API_TOKEN}